slug: isaps
visit: timepoint
charts:
- chart: demo_sex
  title: Sex

webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
