slug: isaps-data-dictionary
visit: timepoint
charts:
- chart: gender
  title: gender

webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
